name: create tag

on:
  workflow_dispatch:
    inputs:
      release_count:
        description: 'Release count'
        required: true
        type: string
        default: '01'
      url:
        description: 'URL'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: tagging
        env:
          TZ: Asia/Tokyo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=`date +"%Y%m%d"`
          TAG_NAME="release-$DATE${{ github.event.inputs.tag_name }}"
          git tag -a "$TAG_NAME" -m  "${{ github.event.inputs.url }}"
          git push origin "$TAG_NAME"
