name: create tag

on:
  workflow_dispatch:
    inputs:
      release_count:
        description: 'count'
        required: true
        type: string
        default: '01'
      kibela_url:
        description: 'URL'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: tagging
        env:
          TZ: Asia/Tokyo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=`date +"%Y%m%d"`
          TAG_NAME="sample-$DATE${{ github.event.inputs.tag_name }}"
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "$TAG_NAME" -m  "${{ github.event.inputs.kibela_url }}"
          git push origin "$TAG_NAME"
